config/routes.rb
Rails.application.routes.draw do
  root :to => "reviews#index"
  resources :reviews do
    collection do
      get 'login'
      get 'register'
      post 'newuser'
      post 'validate'
      post 'search'
      post 'comment'
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :reviews
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
    validates :title, :presence => true
    validates :poster, :presence => true
    has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
    validates :userid, :uniqueness => true

    def self.authenticate(user, password)
        name = self.find_by_userid(user)
        if (name)
            if name.password != password
                name = nil
            end
        end
        name
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.order('id desc').limit(5)
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    if (session[:user_id])
      @review = Review.new
      respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @review }
      end
    else
       flash[:notice] = "Please log on to post"
       redirect_to '/reviews'
    end
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    def comment
        Review.find(params[:id]).comments.create(params[:comment])
        redirect_to :action => "show", :id => params[:id]
    end

    def search
        pattern = params[:searchFor]
        pattern = "%" + pattern + "%"

        @reviews = Review.where("title like ?", pattern)
    end

    def newuser
        respond_to do |format|
            user = User.new
            user.userid = params[:userid]
            user.password = params[:password]
            user.fullname = params[:fullname]
            user.email = params[:email]
        if user.save
            session[:user_id] = user.userid
            flash[:notice] = 'New User ID was successfully created.'
        else
            flash[:notice] = 'Sorry, User ID already exists.'
        end
            format.html {redirect_to '/reviews' }
        end
    end

    def validate

    respond_to do |format|
        user = User.authenticate(params[:userid], params[:password])
        if user
            session[:user_id] = user.userid
            flash[:notice] = 'User successfully logged in'
        else
            flash[:notice] = 'Invalid user/password'
        end
        format.html {redirect_to '/reviews' }
        end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:poster, :date, :article)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Restaurant</title>
  <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>

      <%= csrf_meta_tag %>
</head>

<body>
  <div id="header">
    <h1>Restaurant Reviews</h1>
    <h4>    Finding places to eat</h4>
  </div>
  <div id="content">
    <div id="navigation">
      <h2>Welcome</h2>
      <br />
      <strong><%= link_to 'Home', '/reviews' %><br /><br /></strong>
      <strong><%= link_to 'Login to post', { :action => :login} %><br /></strong>
      <p style="color: green">
        <%= flash[:notice] %>
      </p>
      <strong><%= link_to 'Register for free login', {:action => :register} %><br /></strong>

      <strong><%= link_to 'Post a new review', new_review_path %><br /></strong>
      <br />
      <%= form_tag :action=>'search' do %>
        <label><font color="#663300" size="-1">Search for review:</font>
        </label>
        <%= text_field_tag :searchFor %>
          <%= submit_tag "Find" %>
            <% end %>
    </div>
    <div id="main">
      <p style="color: green">
        <%= flash[:notice] %>
      </p>
      <%= yield %>
    </div>
    <div id="news">
    <h2>What's cookin'</h2><br />
    The latest restaurant news<br />
    <%= render( :partial => "news") %>
    </div>
  </div>
  <div id="footer">
    <a href="mailto:myuser@myhost.com"><font size="1">Contact Us</font></a><font size="1"> | &copy;2014 Restaurant Reviews, LLC </font>
  </div>
</body>

</html>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :poster %><br>
    <%= f.text_field :poster %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :article %><br>
    <%= f.text_area :article %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_news.html.erb
<p>
    <% news = News.order('date desc').limit(2) %>
    <% for item in news %>
      <b><%= item.title %></b><br />
      <%= item.date %><br />
      <%= item.article %><br /><br />
    <% end %>
    </p>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Restaurant reviews</h1>
    <% for review in @reviews %>
       <%= link_to review.title, review %>  submitted by <%= review.poster %><br />
       <%= review.date %><br />
       <%= review.article %><br /><br />
    <% end %>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/login.html.erb
<h1>Please Login</h1>
<%= form_tag :action => 'validate' do %>
  <p>
    <b>User ID</b><br />
    <%= text_field_tag :userid %>
  </p>

  <p>
    <b>Password</b><br />
    <%= password_field_tag :password %>
  </p>
  <p>
    <%= submit_tag "Login" %>
  </p>
<% end %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/register.html.erb
<h1>Register for new account</h1>
<%= form_tag :action => 'newuser' do %>
  <p>
    <b>User ID</b><br />
    <%= text_field_tag :userid %>
  </p>

  <p>
    <b>Full Name</b><br />
    <%= text_field_tag :fullname %>
  </p>

  <p>
    <b>Password</b><br />
    <%= password_field_tag :password %>
  </p>

  <p>
    <b>E-mail</b><br />
    <%= text_field_tag :email %>
  </p>

  <p>
    <%= submit_tag "Create Account" %>
  </p>
<% end %>

app/views/reviews/search.html.erb
<h2>Search Results</h2>
<% for review in @reviews %>
    <br /><%= link_to review.title, review %> submitted by <%= review.poster %><br />
    on <%= review.date %><br />    
<% end %>

app/views/reviews/show.html.erb
<h2><%= @review.title %></h2>
<p>
  Posted by:<%= @review.poster %>
  on <%= @review.date %>
</p>
<p>
  <b>Review:</b><br />
  <%= @review.article %>
</p>

<p>
   <h2>Comments:</h2>
   <% for comment in @review.comments.reverse %>
   posted by: <%= comment.poster %><br />
       on: <%= comment.date %><br />
   <%= comment.comment %><br /><br />
   <% end %>
</p>
<hr />
<h2>Submit new comment:</h2>
<%= form_tag :action => 'comment', :id => @review do %>
<strong>Poster: </strong><%= text_field "comment", "poster" %><br /><br />
<strong>Date: </strong><%= datetime_select "comment", "date" %><br /><br />
<strong>Comment:</strong><br />
<%= text_area "comment", "comment", :rows => 5 %><br />
<%= submit_tag "Comment" %>
<% end %>

<%= link_to 'Edit review', edit_review_path(@review) %> |
<%= link_to 'Back to main menu', reviews_path %>